version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "docker/common/nxdt_requirements.txt"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
